name: Run tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test, lint, format check
    runs-on: ubuntu-20.04
    container:
      image: lukaszkostka/librouteros:${{ matrix.python-version }}
      env:
        CI: yes
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0
          fetch-tags: true

      - name: Move images
        run: mv /opt/* $GITHUB_WORKSPACE/images/

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install library
        run: uv sync --all-extras --dev

      - name: Run Ruff
        run: uv run ruff check .

      - name: Type check
        run: uv run mypy src

      - name: Format
        run: >
          uv run ruff format --diff
          src
          tests

      - name: Unit tests
        run: uv run pytest tests/unit

      - name: Integration tests
        timeout-minutes: 20
        run: uv run pytest -n auto tests/integration
